### ISSUE TITLE
No module named local

### ISSUE THREAD

**Issue by fooying** [akun/PyHackerNews#2]
安装完毕后执行make run报错

```
(venv)root@li704-112:/opt/www/hackernews# make run
cd src && python manage.py runserver 0.0.0.0:
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/www/hackernews/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/opt/www/hackernews/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/www/hackernews/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/opt/www/hackernews/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/opt/www/hackernews/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/opt/www/hackernews/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/www/hackernews/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'pyhn.settings.local' (Is it on sys.path? Is there an import error in the settings file?): No module named local
Makefile:45: recipe for target 'run' failed
```

**Comment by fooying** [comment]
需要修改setting下的local.example.py为local.py

**Comment by akun** [comment]
类似 #1 

完善了安装文档说明，会涉及这步操作
